### ISSUE TITLE
Entry point not found

### ISSUE THREAD

**Issue by cpkio** [RMichelsen/Nvy#12]
Cannot run Nvy on a notebook: "Entry point to GetDpiFromDpiAwarenessContext in Nvy.exe not found" (text originally in Russian, translated by me).

**Comment by RMichelsen** [comment]
Seems to be due to the minimum requirement of `Windows 10, version 1803 [desktop apps only]` 

See:
[GetDpiFromDpiAwarenessContext](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpifromdpiawarenesscontext) 

I'll see if there's a way to determine and only use it if there is support.

**Comment by RMichelsen** [comment]
I've tried using an older API, which should support down to `Windows 10, version 1607`.
Please see if this works for you in the [New Release](https://github.com/RMichelsen/Nvy/releases/tag/v0.1.6)

**Comment by cpkio** [comment]
It works, thanks.

**Comment by dseeni** [comment]
Hey @RMichelsen,
Is it possible to compile nvy for windows 8.1? Is there something I can change to compile for the windows 8.1 api?

My work machine is stuck on windows 8.1... I'd really like to use Nvy.
