### ISSUE TITLE
Are color schemes supported?

### ISSUE THREAD

**Issue by amn** [RMichelsen/Nvy#33]
Hi,

Can't really tell if it's Nvy that should support/delegate support for color schemes, but it doesn't seem switching color schemes (tried Solarized and Papercolor) does much, or shows any of their defined colors. I am no expert on Neovim internals, so can't really tell where to address the question.

**Comment by RMichelsen** [comment]
Color schemes should work just fine. Neovim comes with some default colorschemes you can choose from:
![image](https://user-images.githubusercontent.com/42123601/121950472-f4561e00-cd59-11eb-9f25-464c1353d1cb.png)

Otherwise you need to install a theme such as [gruvbox](https://github.com/morhetz/gruvbox) (the one in the README screenshot)

To apply a colorscheme type `:colorscheme NAME`, e.g. `:colorscheme evening` or put it in your `init.vim` or `init.lua` depending on what you use.

**Comment by amn** [comment]
Thank you for the confirmation. I can't get Solarized to work, must be something wrong with it. I'll continue trying.

**Comment by RMichelsen** [comment]
I'm pretty sure this shouldn't have anything to do with `Nvy`, please open a new issue with a way to reproduce the issue if it remains a problem.
